export const MAX_HOUSEHOLD_NAME_LENGTH = 100;
export const MIN_HOUSEHOLD_NAME_LENGTH = 2;

export const MAX_MEAL_NAME_LENGTH = 150;

export const MAX_PRIORITY_TITLE_LENGTH = 200;

export const INVITATION_EXPIRATION_DAYS = 7;

export const MIN_MEAL_RECOMMENDATIONS = 3;

export const RECOMMENDATION_PERFORMANCE_TARGET_MS = 3000;
export const DASHBOARD_PERFORMANCE_TARGET_MS = 2000;
export const BUDGET_PERFORMANCE_TARGET_MS = 250;

export const PAGINATION_DEFAULT_PAGE_SIZE = 20;
export const PAGINATION_MAX_PAGE_SIZE = 100;

export const FREQUENCIES = ["DAILY", "WEEKLY", "BIWEEKLY", "MONTHLY"] as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;
